version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Permission
          command: 'chmod +x ./gradlew'

      - run:
          name: Generate Antlr
          command: './gradlew :platform:pansyqq:genAntlr'

      - run:
          name: Run Assemble
          command: './gradlew :platform:pansyqq:assembleRelease --info --warning-mode=all'

      - store_artifacts:
          path: 'platform/pansyqq/build/outputs/apk/release'

      - store_artifacts:
          path: '.'
